"""Declarative rule catalog consumed by `modelaudit.rules`."""

from dataclasses import dataclass


@dataclass(frozen=True)
class RuleCatalogEntry:
    """Single declarative rule definition."""

    code: str
    name: str
    severity: str
    description: str
    patterns: tuple[str, ...]


RULE_CATALOG: tuple[RuleCatalogEntry, ...] = (
    RuleCatalogEntry(
        code="S101",
        name="os module import",
        severity="CRITICAL",
        description="Operating system command execution via os module",
        patterns=(r"import\s+os\b", r"from\s+os\s+import", r"__import__\(['\"]os['\"]"),
    ),
    RuleCatalogEntry(
        code="S102",
        name="sys module import",
        severity="CRITICAL",
        description="System manipulation via sys module",
        patterns=(r"import\s+sys\b", r"from\s+sys\s+import", r"__import__\(['\"]sys['\"]"),
    ),
    RuleCatalogEntry(
        code="S103",
        name="subprocess module import",
        severity="CRITICAL",
        description="Process spawning via subprocess module",
        patterns=(r"import\s+subprocess", r"from\s+subprocess\s+import", r"__import__\(['\"]subprocess['\"]"),
    ),
    RuleCatalogEntry(
        code="S104",
        name="eval/exec usage",
        severity="CRITICAL",
        description="Dynamic code execution via eval or exec",
        patterns=(r"\beval\s*\(", r"\bexec\s*\(", r"eval.*exec"),
    ),
    RuleCatalogEntry(
        code="S105",
        name="compile usage",
        severity="CRITICAL",
        description="Code compilation at runtime",
        patterns=(r"\bcompile\s*\(", r"compile.*function"),
    ),
    RuleCatalogEntry(
        code="S106",
        name="__import__ usage",
        severity="CRITICAL",
        description="Dynamic module importing",
        patterns=(r"__import__\s*\(", r"__import__"),
    ),
    RuleCatalogEntry(
        code="S107",
        name="importlib usage",
        severity="HIGH",
        description="Dynamic import machinery via importlib",
        patterns=(r"import\s+importlib", r"from\s+importlib\s+import", r"importlib\.import_module"),
    ),
    RuleCatalogEntry(
        code="S108",
        name="runpy module usage",
        severity="CRITICAL",
        description="Running Python modules as scripts",
        patterns=(r"import\s+runpy", r"from\s+runpy\s+import", r"runpy\.run_"),
    ),
    RuleCatalogEntry(
        code="S109",
        name="webbrowser module usage",
        severity="CRITICAL",
        description="Opening web browsers programmatically",
        patterns=(r"import\s+webbrowser", r"from\s+webbrowser\s+import", r"webbrowser\.open"),
    ),
    RuleCatalogEntry(
        code="S110",
        name="ctypes module usage",
        severity="HIGH",
        description="Foreign function interface via ctypes",
        patterns=(r"import\s+ctypes", r"from\s+ctypes\s+import", r"ctypes\."),
    ),
    RuleCatalogEntry(
        code="S115",
        name="Builtins code-execution access",
        severity="HIGH",
        description="Access to dangerous builtins that can enable code execution",
        patterns=(r"builtins", r"__builtin__", r"__builtins__"),
    ),
    RuleCatalogEntry(
        code="S201",
        name="Pickle REDUCE opcode",
        severity="CRITICAL",
        description="Arbitrary callable execution via pickle REDUCE",
        patterns=(r"pickle.*REDUCE", r"REDUCE.*opcode", r"dangerous.*REDUCE"),
    ),
    RuleCatalogEntry(
        code="S202",
        name="Pickle INST opcode",
        severity="CRITICAL",
        description="Class instantiation via pickle INST",
        patterns=(r"pickle.*INST", r"INST.*opcode", r"dangerous.*INST"),
    ),
    RuleCatalogEntry(
        code="S203",
        name="Pickle OBJ opcode",
        severity="CRITICAL",
        description="Object construction via pickle OBJ",
        patterns=(r"pickle.*\bOBJ\b", r"\bOBJ\b.*opcode", r"dangerous.*\bOBJ\b"),
    ),
    RuleCatalogEntry(
        code="S204",
        name="Pickle NEWOBJ opcode",
        severity="CRITICAL",
        description="New-style class construction via pickle NEWOBJ",
        patterns=(
            r"pickle.*\bNEWOBJ(?:_EX)?\b",
            r"\bNEWOBJ(?:_EX)?\b.*opcode",
            r"dangerous.*\bNEWOBJ(?:_EX)?\b",
        ),
    ),
    RuleCatalogEntry(
        code="S205",
        name="Pickle STACK_GLOBAL opcode",
        severity="HIGH",
        description="Stack-based global retrieval via pickle",
        patterns=(r"pickle.*STACK_GLOBAL", r"STACK_GLOBAL.*opcode"),
    ),
    RuleCatalogEntry(
        code="S206",
        name="Pickle GLOBAL opcode",
        severity="HIGH",
        description="Global name resolution via pickle",
        patterns=(r"pickle.*GLOBAL", r"GLOBAL.*opcode", r"imports.*module"),
    ),
    RuleCatalogEntry(
        code="S207",
        name="Pickle BUILD opcode",
        severity="MEDIUM",
        description="Object building operations via pickle",
        patterns=(r"pickle.*BUILD", r"BUILD.*opcode"),
    ),
    RuleCatalogEntry(
        code="S208",
        name="Pickle SETATTR opcode",
        severity="HIGH",
        description="Attribute setting via pickle SETATTR",
        patterns=(r"pickle.*SETATTR", r"SETATTR.*opcode"),
    ),
    RuleCatalogEntry(
        code="S209",
        name="Pickle SETITEM opcode",
        severity="MEDIUM",
        description="Item assignment via pickle",
        patterns=(r"pickle.*SETITEM", r"SETITEM.*opcode"),
    ),
    RuleCatalogEntry(
        code="S210",
        name="Pickle SETITEMS opcode",
        severity="MEDIUM",
        description="Multiple item assignment via pickle",
        patterns=(r"pickle.*SETITEMS", r"SETITEMS.*opcode"),
    ),
    RuleCatalogEntry(
        code="S211",
        name="Pickle extension opcode",
        severity="HIGH",
        description="Copyreg extension reference via pickle EXT opcode",
        patterns=(r"pickle.*EXT[124]", r"EXT[124].*opcode", r"copyreg.*extension"),
    ),
    RuleCatalogEntry(
        code="S212",
        name="Pickle persistent ID opcode",
        severity="MEDIUM",
        description="Persistent object resolution via pickle persistent_load callback",
        patterns=(r"pickle.*PERSID", r"PERSID.*opcode", r"persistent_load"),
    ),
    RuleCatalogEntry(
        code="S213",
        name="Nested/encoded pickle payload",
        severity="CRITICAL",
        description="Nested or encoded pickle payload detected",
        patterns=(r"nested.*pickle", r"encoded.*pickle", r"pickle.*payload"),
    ),
    RuleCatalogEntry(
        code="S214",
        name="Pickle expansion denial-of-service",
        severity="HIGH",
        description="Pickle graph expansion pattern can consume excessive memory or CPU",
        patterns=(r"pickle.*expansion", r"memo.*growth", r"excessive.*dup"),
    ),
    RuleCatalogEntry(
        code="S301",
        name="socket module usage",
        severity="HIGH",
        description="Low-level networking via socket module",
        patterns=(r"import\s+socket", r"from\s+socket\s+import", r"socket\."),
    ),
    RuleCatalogEntry(
        code="S302",
        name="requests/urllib usage",
        severity="MEDIUM",
        description="HTTP client operations",
        patterns=(r"import\s+requests", r"import\s+urllib", r"urllib\.request", r"requests\."),
    ),
    RuleCatalogEntry(
        code="S303",
        name="http.client usage",
        severity="MEDIUM",
        description="HTTP protocol handling",
        patterns=(r"import\s+http\.client", r"from\s+http\.client", r"http\.client"),
    ),
    RuleCatalogEntry(
        code="S304",
        name="ftplib usage",
        severity="HIGH",
        description="FTP operations",
        patterns=(r"import\s+ftplib", r"from\s+ftplib", r"ftplib\."),
    ),
    RuleCatalogEntry(
        code="S305",
        name="telnetlib usage",
        severity="HIGH",
        description="Telnet protocol usage",
        patterns=(r"import\s+telnetlib", r"from\s+telnetlib", r"telnetlib\."),
    ),
    RuleCatalogEntry(
        code="S306",
        name="smtplib usage",
        severity="MEDIUM",
        description="Email sending capabilities",
        patterns=(r"import\s+smtplib", r"from\s+smtplib", r"smtplib\."),
    ),
    RuleCatalogEntry(
        code="S307",
        name="DNS lookups",
        severity="MEDIUM",
        description="Domain name resolution detected",
        patterns=(r"socket\.gethostby", r"dns\.", r"getaddrinfo"),
    ),
    RuleCatalogEntry(
        code="S308",
        name="Hardcoded IP addresses",
        severity="LOW",
        description="Static IP addresses found",
        patterns=(r"\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b",),
    ),
    RuleCatalogEntry(
        code="S309",
        name="Hardcoded URLs",
        severity="LOW",
        description="Static URLs found",
        patterns=(r"https?://", r"ftp://", r"ws://"),
    ),
    RuleCatalogEntry(
        code="S310",
        name="Data exfiltration patterns",
        severity="HIGH",
        description="Potential data theft patterns",
        patterns=(r"send.*data", r"post.*sensitive", r"upload.*file", r"exfiltrat"),
    ),
    RuleCatalogEntry(
        code="S401",
        name="open() for write/append",
        severity="MEDIUM",
        description="File write operations detected",
        patterns=(r"open\([^)]*['\"][wax]", r"open\([^)]*mode\s*=\s*['\"][wax]"),
    ),
    RuleCatalogEntry(
        code="S402",
        name="pathlib write operations",
        severity="MEDIUM",
        description="Path-based file writes",
        patterns=(r"Path.*write", r"\.write_text", r"\.write_bytes"),
    ),
    RuleCatalogEntry(
        code="S403",
        name="shutil operations",
        severity="MEDIUM",
        description="File/directory operations via shutil",
        patterns=(r"import\s+shutil", r"shutil\.", r"copy.*file", r"move.*file"),
    ),
    RuleCatalogEntry(
        code="S404",
        name="tempfile operations",
        severity="LOW",
        description="Temporary file creation",
        patterns=(r"import\s+tempfile", r"tempfile\.", r"NamedTemporaryFile"),
    ),
    RuleCatalogEntry(
        code="S405",
        name="Path traversal attempts",
        severity="CRITICAL",
        description="Directory escape attempts detected",
        patterns=(r"\.\./", r"\.\.\\", r"parent/parent", r"traversal"),
    ),
    RuleCatalogEntry(
        code="S406",
        name="Archive link to external location",
        severity="HIGH",
        description="Symbolic or hard archive link pointing outside scope",
        patterns=(r"symlink.*external", r"link.*outside", r"symlink"),
    ),
    RuleCatalogEntry(
        code="S407",
        name="Hidden file access",
        severity="LOW",
        description="Dotfile operations detected",
        patterns=(r"/\.", r"\\\.", r"hidden.*file"),
    ),
    RuleCatalogEntry(
        code="S408",
        name="/etc or system file access",
        severity="HIGH",
        description="System configuration file access",
        patterns=(r"/etc/", r"\\system32\\", r"/usr/bin/", r"/Windows/"),
    ),
    RuleCatalogEntry(
        code="S409",
        name="Home directory access",
        severity="MEDIUM",
        description="User directory operations",
        patterns=(r"~/", r"home/", r"Users/", r"expanduser"),
    ),
    RuleCatalogEntry(
        code="S410",
        name="Archive bomb detected",
        severity="HIGH",
        description="Excessive compression ratio",
        patterns=(r"compression.*bomb", r"zip.*bomb", r"excessive.*ratio"),
    ),
    RuleCatalogEntry(
        code="S501",
        name="Windows PE executable",
        severity="CRITICAL",
        description="Windows binary embedded",
        patterns=(r"PE.*executable", r"Windows.*executable", r"\.exe", r"MZ.*header"),
    ),
    RuleCatalogEntry(
        code="S502",
        name="Linux ELF executable",
        severity="CRITICAL",
        description="Linux binary embedded",
        patterns=(r"ELF.*executable", r"Linux.*executable", r"ELF.*header"),
    ),
    RuleCatalogEntry(
        code="S503",
        name="macOS Mach-O executable",
        severity="CRITICAL",
        description="macOS binary embedded",
        patterns=(r"Mach-O.*executable", r"macOS.*executable", r"Mach-O.*header"),
    ),
    RuleCatalogEntry(
        code="S504",
        name="Shell script",
        severity="CRITICAL",
        description="Shell script embedded",
        patterns=(r"#!/bin/sh", r"#!/bin/bash", r"shell.*script"),
    ),
    RuleCatalogEntry(
        code="S505",
        name="Batch script",
        severity="CRITICAL",
        description="Windows batch script embedded",
        patterns=(r"\.bat\b", r"\.cmd\b", r"batch.*script", r"@echo off"),
    ),
    RuleCatalogEntry(
        code="S506",
        name="PowerShell script",
        severity="CRITICAL",
        description="PowerShell code embedded",
        patterns=(r"\.ps1\b", r"PowerShell", r"Invoke-Expression"),
    ),
    RuleCatalogEntry(
        code="S507",
        name="Python script embedded",
        severity="HIGH",
        description="Python code as string data",
        patterns=(r"python.*script", r"embedded.*python", r"exec.*python"),
    ),
    RuleCatalogEntry(
        code="S508",
        name="JavaScript code",
        severity="HIGH",
        description="JavaScript code embedded",
        patterns=(r"javascript:", r"\.js\b", r"<script"),
    ),
    RuleCatalogEntry(
        code="S509",
        name="WebAssembly module",
        severity="HIGH",
        description="WASM binary embedded",
        patterns=(r"\.wasm\b", r"WebAssembly", r"wasm.*module"),
    ),
    RuleCatalogEntry(
        code="S510",
        name="JIT/TorchScript code",
        severity="MEDIUM",
        description="JIT compiled code detected",
        patterns=(r"TorchScript", r"JIT.*code", r"torch\.jit"),
    ),
    RuleCatalogEntry(
        code="S601",
        name="Base64 encoded payload",
        severity="MEDIUM",
        description="Base64 encoded data detected",
        patterns=(r"base64", r"b64decode", r"base64\.b64"),
    ),
    RuleCatalogEntry(
        code="S602",
        name="Hex encoded payload",
        severity="MEDIUM",
        description="Hexadecimal encoded data",
        patterns=(r"hex.*decode", r"fromhex", r"unhexlify"),
    ),
    RuleCatalogEntry(
        code="S603",
        name="zlib compressed data",
        severity="LOW",
        description="Compressed content detected",
        patterns=(r"zlib", r"compress", r"decompress"),
    ),
    RuleCatalogEntry(
        code="S604",
        name="Encrypted/obfuscated code",
        severity="HIGH",
        description="Encrypted or obfuscated payloads",
        patterns=(r"encrypt", r"obfuscat", r"cipher"),
    ),
    RuleCatalogEntry(
        code="S605",
        name="Unicode encoding tricks",
        severity="MEDIUM",
        description="Unicode obfuscation detected",
        patterns=(r"unicode.*escape", r"\\u[0-9a-f]{4}", r"unicode.*trick"),
    ),
    RuleCatalogEntry(
        code="S606",
        name="ROT13/Caesar cipher",
        severity="LOW",
        description="Simple cipher detected",
        patterns=(r"rot13", r"rot-13", r"caesar"),
    ),
    RuleCatalogEntry(
        code="S607",
        name="XOR obfuscation",
        severity="MEDIUM",
        description="XOR encrypted data",
        patterns=(r"xor.*encrypt", r"xor.*obfuscat", r"\^.*key"),
    ),
    RuleCatalogEntry(
        code="S609",
        name="URL/percent encoding obfuscation",
        severity="LOW",
        description="URL-encoded content used to obfuscate payloads",
        patterns=(r"url.*encode", r"percent.*encoding", r"%[0-9a-fA-F]{2}"),
    ),
    RuleCatalogEntry(
        code="S610",
        name="Custom/unknown encoding",
        severity="MEDIUM",
        description="Custom or unknown encoding used to hide payloads",
        patterns=(r"custom.*encoding", r"unknown.*encoding", r"obfuscat.*encoding"),
    ),
    RuleCatalogEntry(
        code="S701",
        name="API key pattern",
        severity="MEDIUM",
        description="API key detected",
        patterns=(r"api[_-]?key", r"apikey", r"api_secret"),
    ),
    RuleCatalogEntry(
        code="S702",
        name="Password/credential",
        severity="HIGH",
        description="Password or credential detected",
        patterns=(r"password", r"passwd", r"credential", r"secret"),
    ),
    RuleCatalogEntry(
        code="S703",
        name="Private key",
        severity="HIGH",
        description="Private cryptographic key detected",
        patterns=(r"BEGIN.*PRIVATE", r"private[_-]?key", r"ssh-rsa"),
    ),
    RuleCatalogEntry(
        code="S704",
        name="AWS credentials",
        severity="HIGH",
        description="AWS access keys detected",
        patterns=(r"AKIA[0-9A-Z]{16}", r"aws[_-]?access", r"aws[_-]?secret"),
    ),
    RuleCatalogEntry(
        code="S705",
        name="GCP/Azure credentials",
        severity="HIGH",
        description="Cloud provider credentials",
        patterns=(r"azure.*key", r"gcp.*credential", r"google.*api"),
    ),
    RuleCatalogEntry(
        code="S706",
        name="Database connection string",
        severity="HIGH",
        description="Database connection URL detected",
        patterns=(r"mongodb://", r"postgresql://", r"mysql://", r"sqlite://"),
    ),
    RuleCatalogEntry(
        code="S707",
        name="JWT token",
        severity="MEDIUM",
        description="JSON Web Token detected",
        patterns=(r"eyJ[A-Za-z0-9_-]+\.", r"jwt", r"bearer.*token"),
    ),
    RuleCatalogEntry(
        code="S708",
        name="OAuth token",
        severity="MEDIUM",
        description="OAuth token detected",
        patterns=(r"oauth", r"access[_-]?token", r"refresh[_-]?token"),
    ),
    RuleCatalogEntry(
        code="S709",
        name="Webhook URL",
        severity="LOW",
        description="Webhook endpoint detected",
        patterns=(r"webhook", r"hook.*url", r"callback.*url"),
    ),
    RuleCatalogEntry(
        code="S710",
        name="High entropy strings",
        severity="LOW",
        description="Random-looking string detected",
        patterns=(r"entropy.*high", r"random.*string", r"suspicious.*entropy"),
    ),
    RuleCatalogEntry(
        code="S801",
        name="Suspicious weight distribution",
        severity="LOW",
        description="Statistical anomalies in weights",
        patterns=(r"weight.*distribution", r"suspicious.*weight", r"anomal.*weight"),
    ),
    RuleCatalogEntry(
        code="S802",
        name="Outlier neurons",
        severity="LOW",
        description="Extreme weight values detected",
        patterns=(r"outlier.*neuron", r"extreme.*weight", r"sigma.*deviation"),
    ),
    RuleCatalogEntry(
        code="S803",
        name="Dissimilar weight vectors",
        severity="LOW",
        description="Inconsistent weight patterns",
        patterns=(r"dissimilar.*weight", r"inconsistent.*pattern", r"weight.*vector"),
    ),
    RuleCatalogEntry(
        code="S804",
        name="Excessive model dimensions",
        severity="LOW",
        description="Unusually large layer dimensions",
        patterns=(r"excessive.*dimension", r"large.*layer", r"dimension.*exceed"),
    ),
    RuleCatalogEntry(
        code="S805",
        name="Unusual layer configuration",
        severity="LOW",
        description="Non-standard architecture detected",
        patterns=(r"unusual.*layer", r"non-standard.*architecture", r"strange.*config"),
    ),
    RuleCatalogEntry(
        code="S806",
        name="Hidden layers in manifest",
        severity="MEDIUM",
        description="Undocumented layers found",
        patterns=(r"hidden.*layer", r"undocumented.*layer", r"missing.*manifest"),
    ),
    RuleCatalogEntry(
        code="S807",
        name="Backdoor trigger patterns",
        severity="HIGH",
        description="Potential backdoor detected",
        patterns=(r"backdoor", r"trigger.*pattern", r"trojan"),
    ),
    RuleCatalogEntry(
        code="S808",
        name="Weight manipulation signs",
        severity="MEDIUM",
        description="Signs of tampered weights",
        patterns=(r"weight.*manipulat", r"tamper.*weight", r"modif.*weight"),
    ),
    RuleCatalogEntry(
        code="S809",
        name="Non-standard activations",
        severity="LOW",
        description="Custom activation functions",
        patterns=(r"custom.*activation", r"non-standard.*activation", r"unknown.*activation"),
    ),
    RuleCatalogEntry(
        code="S810",
        name="Custom layers with code",
        severity="MEDIUM",
        description="Layers containing executable code",
        patterns=(r"custom.*layer.*code", r"lambda.*layer", r"layer.*function"),
    ),
    RuleCatalogEntry(
        code="S901",
        name="File type mismatch",
        severity="MEDIUM",
        description="Extension doesn't match content",
        patterns=(r"type.*mismatch", r"extension.*mismatch", r"format.*conflict"),
    ),
    RuleCatalogEntry(
        code="S902",
        name="Corrupted file structure",
        severity="LOW",
        description="Invalid file format detected",
        patterns=(r"corrupt", r"invalid.*structure", r"malformed"),
    ),
    RuleCatalogEntry(
        code="S903",
        name="Invalid magic bytes",
        severity="LOW",
        description="Wrong file signature",
        patterns=(r"magic.*bytes", r"invalid.*signature", r"wrong.*header"),
    ),
    RuleCatalogEntry(
        code="S904",
        name="Excessive file size",
        severity="LOW",
        description="File exceeds size limits",
        patterns=(r"file.*too.*large", r"excessive.*size", r"size.*limit"),
    ),
    RuleCatalogEntry(
        code="S905",
        name="Suspicious file metadata",
        severity="LOW",
        description="Unusual metadata detected",
        patterns=(r"suspicious.*metadata", r"unusual.*metadata", r"metadata.*anomaly"),
    ),
    RuleCatalogEntry(
        code="S906",
        name="Non-standard file extension",
        severity="LOW",
        description="Uncommon file extension",
        patterns=(r"unknown.*extension", r"non-standard.*extension", r"unusual.*extension"),
    ),
    RuleCatalogEntry(
        code="S907",
        name="Multiple format markers",
        severity="MEDIUM",
        description="Multiple file format indicators",
        patterns=(r"multiple.*format", r"polyglot.*indicator", r"dual.*format"),
    ),
    RuleCatalogEntry(
        code="S908",
        name="Polyglot file detected",
        severity="HIGH",
        description="File valid as multiple formats",
        patterns=(r"polyglot", r"multiple.*valid.*format", r"dual.*purpose"),
    ),
    RuleCatalogEntry(
        code="S999",
        name="Binary scan error",
        severity="LOW",
        description="Scanner encountered an unexpected binary parsing error",
        patterns=(r"binary.*scan.*error", r"scan.*exception", r"parsing.*error"),
    ),
    RuleCatalogEntry(
        code="S1001",
        name="Blacklisted model name",
        severity="CRITICAL",
        description="Known malicious model name",
        patterns=(r"blacklist", r"malicious.*model", r"banned.*name"),
    ),
    RuleCatalogEntry(
        code="S1002",
        name="Known malicious hash",
        severity="CRITICAL",
        description="File matches malware signature",
        patterns=(r"malicious.*hash", r"malware.*signature", r"virus.*detect"),
    ),
    RuleCatalogEntry(
        code="S1003",
        name="Typosquatting detection",
        severity="HIGH",
        description="Name similar to popular model",
        patterns=(r"typosquat", r"similar.*name", r"confusing.*name"),
    ),
    RuleCatalogEntry(
        code="S1004",
        name="Unsigned model",
        severity="LOW",
        description="Model lacks digital signature",
        patterns=(r"unsigned", r"no.*signature", r"missing.*signature"),
    ),
    RuleCatalogEntry(
        code="S1005",
        name="Invalid signature",
        severity="HIGH",
        description="Digital signature verification failed",
        patterns=(r"invalid.*signature", r"bad.*signature", r"signature.*fail"),
    ),
    RuleCatalogEntry(
        code="S1006",
        name="Expired certificate",
        severity="LOW",
        description="Signing certificate has expired",
        patterns=(r"expired.*cert", r"outdated.*cert", r"cert.*expired"),
    ),
    RuleCatalogEntry(
        code="S1007",
        name="Untrusted repository",
        severity="MEDIUM",
        description="Model from unknown source",
        patterns=(r"untrusted.*source", r"unknown.*repository", r"unverified.*origin"),
    ),
    RuleCatalogEntry(
        code="S1008",
        name="License incompatibility",
        severity="LOW",
        description="License conflicts detected",
        patterns=(r"license.*incompatib", r"license.*conflict", r"license.*violation"),
    ),
    RuleCatalogEntry(
        code="S1009",
        name="GPL in proprietary use",
        severity="LOW",
        description="GPL license in commercial context",
        patterns=(r"GPL.*proprietary", r"GPL.*commercial", r"copyleft.*violation"),
    ),
    RuleCatalogEntry(
        code="S1010",
        name="Missing provenance",
        severity="LOW",
        description="No source tracking information",
        patterns=(r"missing.*provenance", r"no.*source.*track", r"unknown.*origin"),
    ),
    RuleCatalogEntry(
        code="S1101",
        name="PyTorch unsafe load",
        severity="HIGH",
        description="torch.load without weights_only=True",
        patterns=(r"torch\.load", r"unsafe.*pytorch", r"pickle.*pytorch"),
    ),
    RuleCatalogEntry(
        code="S1102",
        name="TensorFlow SavedModel risks",
        severity="MEDIUM",
        description="TensorFlow SavedModel security issues",
        patterns=(r"savedmodel", r"tensorflow.*risk", r"tf\.saved_model"),
    ),
    RuleCatalogEntry(
        code="S1103",
        name="Keras Lambda layers",
        severity="MEDIUM",
        description="Keras Lambda layers with code",
        patterns=(r"Lambda.*layer", r"keras.*lambda", r"custom.*keras.*function"),
    ),
    RuleCatalogEntry(
        code="S1104",
        name="ONNX opset version",
        severity="LOW",
        description="ONNX version compatibility issue",
        patterns=(r"onnx.*version", r"opset.*version", r"onnx.*compatibility"),
    ),
    RuleCatalogEntry(
        code="S1105",
        name="JAX compilation risks",
        severity="MEDIUM",
        description="JAX JIT compilation security",
        patterns=(r"jax.*compilation", r"jax\.jit", r"jax.*security"),
    ),
    RuleCatalogEntry(
        code="S1106",
        name="MXNet custom operators",
        severity="MEDIUM",
        description="MXNet custom operator risks",
        patterns=(r"mxnet.*custom", r"mxnet.*operator", r"mxnet.*op"),
    ),
    RuleCatalogEntry(
        code="S1107",
        name="PaddlePaddle dynamic graph",
        severity="MEDIUM",
        description="PaddlePaddle dynamic mode risks",
        patterns=(r"paddle.*dynamic", r"paddlepaddle", r"paddle.*graph"),
    ),
    RuleCatalogEntry(
        code="S1108",
        name="CoreML custom layers",
        severity="MEDIUM",
        description="CoreML custom layer risks",
        patterns=(r"coreml.*custom", r"coreml.*layer", r"mlmodel.*custom"),
    ),
    RuleCatalogEntry(
        code="S1109",
        name="TensorRT plugins",
        severity="MEDIUM",
        description="TensorRT plugin security",
        patterns=(r"tensorrt.*plugin", r"trt.*plugin", r"tensorrt.*custom"),
    ),
    RuleCatalogEntry(
        code="S1110",
        name="GGUF/GGML format risks",
        severity="LOW",
        description="GGUF/GGML format security issues",
        patterns=(r"gguf", r"ggml", r"llama.*format"),
    ),
    RuleCatalogEntry(
        code="S1111",
        name="ONNX custom operator domains",
        severity="INFO",
        description="ONNX model may depend on an external custom operator implementation",
        patterns=(
            r"onnx.*custom.*operator",
            r"custom onnx operator",
            r"custom operator domain",
            r"custom.*onnx.*domain",
        ),
    ),
)
