"""Static scanner registry metadata shared by scanner loading and utility code."""

from __future__ import annotations

from typing import Any

SCANNER_REGISTRY_METADATA: dict[str, dict[str, Any]] = {
    "pickle": {
        "module": "modelaudit.scanners.pickle_scanner",
        "class": "PickleScanner",
        "description": "Scans pickle files for malicious code",
        "extensions": [".pkl", ".pickle", ".dill", ".pt", ".pth", ".ckpt"],
        "priority": 1,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "pytorch_binary": {
        "module": "modelaudit.scanners.pytorch_binary_scanner",
        "class": "PyTorchBinaryScanner",
        "description": "Scans PyTorch binary files",
        "extensions": [".bin"],
        "priority": 3,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "tf_savedmodel": {
        "module": "modelaudit.scanners.tf_savedmodel_scanner",
        "class": "TensorFlowSavedModelScanner",
        "description": "Scans TensorFlow SavedModel files",
        "extensions": [".pb", ""],
        "priority": 4,
        "dependencies": ["tensorflow"],
        "numpy_sensitive": True,
    },
    "tf_metagraph": {
        "module": "modelaudit.scanners.tf_metagraph_scanner",
        "class": "TensorFlowMetaGraphScanner",
        "description": "Scans TensorFlow MetaGraph .meta files",
        "extensions": [".meta"],
        "priority": 4,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "keras_zip": {
        "module": "modelaudit.scanners.keras_zip_scanner",
        "class": "KerasZipScanner",
        "description": "Scans ZIP-based Keras model files",
        "extensions": [".keras"],
        "priority": 4,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "keras_h5": {
        "module": "modelaudit.scanners.keras_h5_scanner",
        "class": "KerasH5Scanner",
        "description": "Scans Keras H5 model files",
        "extensions": [".h5", ".hdf5", ".keras"],
        "priority": 5,
        "dependencies": ["h5py"],
        "numpy_sensitive": True,
    },
    "onnx": {
        "module": "modelaudit.scanners.onnx_scanner",
        "class": "OnnxScanner",
        "description": "Scans ONNX model files",
        "extensions": [".onnx"],
        "priority": 6,
        "dependencies": ["onnx"],
        "numpy_sensitive": True,
    },
    "coreml": {
        "module": "modelaudit.scanners.coreml_scanner",
        "class": "CoreMLScanner",
        "description": "Scans CoreML .mlmodel files",
        "extensions": [".mlmodel"],
        "priority": 7,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "openvino": {
        "module": "modelaudit.scanners.openvino_scanner",
        "class": "OpenVinoScanner",
        "description": "Scans OpenVINO IR model files",
        "extensions": [".xml"],
        "priority": 6,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "pytorch_zip": {
        "module": "modelaudit.scanners.pytorch_zip_scanner",
        "class": "PyTorchZipScanner",
        "description": "Scans PyTorch ZIP-based model files",
        "extensions": [".pt", ".pth", ".ckpt", ".pkl", ".bin"],
        "priority": 2,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "executorch": {
        "module": "modelaudit.scanners.executorch_scanner",
        "class": "ExecuTorchScanner",
        "description": "Scans ExecuTorch mobile archives",
        "extensions": [".ptl", ".pte"],
        "priority": 6,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "gguf": {
        "module": "modelaudit.scanners.gguf_scanner",
        "class": "GgufScanner",
        "description": "Scans GGUF/GGML model files",
        "extensions": [".gguf", ".ggml"],
        "priority": 7,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "joblib": {
        "module": "modelaudit.scanners.joblib_scanner",
        "class": "JoblibScanner",
        "description": "Scans joblib serialized files",
        "extensions": [".joblib"],
        "priority": 8,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "r_serialized": {
        "module": "modelaudit.scanners.r_serialized_scanner",
        "class": "RSerializedScanner",
        "description": "Scans R serialized model files",
        "extensions": [".rds", ".rda", ".rdata"],
        "priority": 8,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "skops": {
        "module": "modelaudit.scanners.skops_scanner",
        "class": "SkopsScanner",
        "description": "Scans skops files for CVE-2025-54412, CVE-2025-54413, CVE-2025-54886",
        "extensions": [".skops"],
        "priority": 8,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "numpy": {
        "module": "modelaudit.scanners.numpy_scanner",
        "class": "NumPyScanner",
        "description": "Scans NumPy array files",
        "extensions": [".npy", ".npz"],
        "priority": 9,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "oci_layer": {
        "module": "modelaudit.scanners.oci_layer_scanner",
        "class": "OciLayerScanner",
        "description": "Scans OCI container layers",
        "extensions": [".manifest"],
        "priority": 10,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "text": {
        "module": "modelaudit.scanners.text_scanner",
        "class": "TextScanner",
        "description": "Scans ML-related text files",
        "extensions": [".txt", ".md", ".markdown", ".rst"],
        "priority": 11,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "manifest": {
        "module": "modelaudit.scanners.manifest_scanner",
        "class": "ManifestScanner",
        "description": "Scans manifest and configuration files",
        "extensions": [
            ".json",
            ".yaml",
            ".yml",
            ".xml",
            ".toml",
            ".ini",
            ".cfg",
            ".config",
            ".manifest",
            ".model",
            ".metadata",
        ],
        "priority": 12,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "pmml": {
        "module": "modelaudit.scanners.pmml_scanner",
        "class": "PmmlScanner",
        "description": "Scans PMML model files",
        "extensions": [".pmml"],
        "priority": 12,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "weight_distribution": {
        "module": "modelaudit.scanners.weight_distribution_scanner",
        "class": "WeightDistributionScanner",
        "description": "Analyzes weight distributions for anomalies",
        "extensions": [
            ".pt",
            ".pth",
            ".h5",
            ".keras",
            ".hdf5",
            ".pb",
            ".onnx",
        ],
        "priority": 13,
        "dependencies": ["torch", "h5py", "tensorflow", "onnx", "safetensors"],
        "numpy_sensitive": True,
    },
    "safetensors": {
        "module": "modelaudit.scanners.safetensors_scanner",
        "class": "SafeTensorsScanner",
        "description": "Scans SafeTensors model files",
        "extensions": [".safetensors"],
        "priority": 14,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "flax_msgpack": {
        "module": "modelaudit.scanners.flax_msgpack_scanner",
        "class": "FlaxMsgpackScanner",
        "description": "Scans Flax/JAX msgpack checkpoint files with enhanced security analysis",
        "extensions": [".msgpack", ".flax", ".orbax", ".jax"],
        "priority": 15,
        "dependencies": ["msgpack"],
        "numpy_sensitive": False,
    },
    "jax_checkpoint": {
        "module": "modelaudit.scanners.jax_checkpoint_scanner",
        "class": "JaxCheckpointScanner",
        "description": "Scans JAX checkpoint files in various serialization formats",
        "extensions": [".ckpt", ".checkpoint", ".orbax-checkpoint", ".pickle"],
        "priority": 15,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "tflite": {
        "module": "modelaudit.scanners.tflite_scanner",
        "class": "TFLiteScanner",
        "description": "Scans TensorFlow Lite model files",
        "extensions": [".tflite", ".bin"],
        "priority": 2,
        "dependencies": ["tflite"],
        "numpy_sensitive": True,
    },
    "tensorrt": {
        "module": "modelaudit.scanners.tensorrt_scanner",
        "class": "TensorRTScanner",
        "description": "Scans TensorRT engine files",
        "extensions": [".engine", ".plan", ".trt"],
        "priority": 17,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "paddle": {
        "module": "modelaudit.scanners.paddle_scanner",
        "class": "PaddleScanner",
        "description": "Scans PaddlePaddle model files",
        "extensions": [".pdmodel", ".pdiparams"],
        "priority": 18,
        "dependencies": ["paddlepaddle"],
        "numpy_sensitive": True,
    },
    "cntk": {
        "module": "modelaudit.scanners.cntk_scanner",
        "class": "CntkScanner",
        "description": "Scans CNTK .dnn/.cmf model artifacts",
        "extensions": [".dnn", ".cmf"],
        "priority": 18,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "rknn": {
        "module": "modelaudit.scanners.rknn_scanner",
        "class": "RknnScanner",
        "description": "Scans Rockchip RKNN model files",
        "extensions": [".rknn"],
        "priority": 19,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "torch7": {
        "module": "modelaudit.scanners.torch7_scanner",
        "class": "Torch7Scanner",
        "description": "Scans legacy Torch7 serialized model files",
        "extensions": [".t7", ".th", ".net"],
        "priority": 19,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "tar": {
        "module": "modelaudit.scanners.tar_scanner",
        "class": "TarScanner",
        "description": "Scans TAR archive files",
        "extensions": [".tar", ".tar.gz", ".tgz", ".tar.bz2", ".tbz2", ".tar.xz", ".txz"],
        "priority": 98,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "jinja2_template": {
        "module": "modelaudit.scanners.jinja2_template_scanner",
        "class": "Jinja2TemplateScanner",
        "description": "Scans for Jinja2 template injection vulnerabilities in ML models",
        "extensions": [".gguf", ".json", ".yaml", ".yml", ".jinja", ".j2", ".template"],
        "priority": 14,
        "dependencies": ["jinja2", "gguf"],
        "numpy_sensitive": False,
    },
    "metadata": {
        "module": "modelaudit.scanners.metadata_scanner",
        "class": "MetadataScanner",
        "description": "Scans model metadata files for security issues",
        "extensions": [".json", ".md", ".markdown", ".rst", ".yml", ".yaml"],
        "priority": 1,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "sevenzip": {
        "module": "modelaudit.scanners.sevenzip_scanner",
        "class": "SevenZipScanner",
        "description": "Scans 7-Zip archive files",
        "extensions": [".7z"],
        "priority": 97,
        "dependencies": ["py7zr"],
        "numpy_sensitive": False,
    },
    "lightgbm": {
        "module": "modelaudit.scanners.lightgbm_scanner",
        "class": "LightGBMScanner",
        "description": "Scans native LightGBM model files",
        "extensions": [".model", ".txt", ".lgb", ".lightgbm"],
        "priority": 6,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "llamafile": {
        "module": "modelaudit.scanners.llamafile_scanner",
        "class": "LlamafileScanner",
        "description": "Scans Llamafile executable model artifacts",
        "extensions": [".llamafile", ".exe", ""],
        "priority": 6,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "xgboost": {
        "module": "modelaudit.scanners.xgboost_scanner",
        "class": "XGBoostScanner",
        "description": "Scans XGBoost model files for security vulnerabilities",
        "extensions": [".bst", ".model", ".json", ".ubj"],
        "priority": 7,
        "dependencies": ["xgboost", "ubjson"],
        "numpy_sensitive": True,
    },
    "mxnet": {
        "module": "modelaudit.scanners.mxnet_scanner",
        "class": "MXNetScanner",
        "description": "Scans MXNet symbol/params model artifacts",
        "extensions": [".json", ".params"],
        "priority": 8,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "catboost": {
        "module": "modelaudit.scanners.catboost_scanner",
        "class": "CatBoostScanner",
        "description": "Scans CatBoost .cbm model files for suspicious metadata indicators",
        "extensions": [".cbm"],
        "priority": 8,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "nemo": {
        "module": "modelaudit.scanners.nemo_scanner",
        "class": "NemoScanner",
        "description": "Scans NVIDIA NeMo model files for Hydra _target_ injection",
        "extensions": [".nemo"],
        "priority": 14,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "torchserve_mar": {
        "module": "modelaudit.scanners.torchserve_mar_scanner",
        "class": "TorchServeMarScanner",
        "description": "Scans TorchServe .mar model archive files",
        "extensions": [".mar"],
        "priority": 96,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "compressed": {
        "module": "modelaudit.scanners.compressed_scanner",
        "class": "CompressedScanner",
        "description": "Scans standalone compressed wrappers and forwards decompressed payloads",
        "extensions": [".gz", ".bz2", ".xz", ".lz4", ".zlib"],
        "priority": 95,
        "dependencies": [],
        "numpy_sensitive": False,
    },
    "zip": {
        "module": "modelaudit.scanners.zip_scanner",
        "class": "ZipScanner",
        "description": "Scans ZIP archive files",
        "extensions": [".zip", ".npz", ".mar"],
        "priority": 99,
        "dependencies": [],
        "numpy_sensitive": False,
    },
}


def get_scanner_registry_metadata() -> dict[str, dict[str, Any]]:
    """Return a mutable copy of the static scanner registry metadata."""
    metadata: dict[str, dict[str, Any]] = {}
    for scanner_id, scanner_info in SCANNER_REGISTRY_METADATA.items():
        copied_info = dict(scanner_info)

        extensions = copied_info.get("extensions")
        if isinstance(extensions, list):
            copied_info["extensions"] = list(extensions)

        dependencies = copied_info.get("dependencies")
        if isinstance(dependencies, list):
            copied_info["dependencies"] = list(dependencies)

        metadata[scanner_id] = copied_info

    return metadata
