name: Feature request
description: Suggest an improvement for ModelAudit.
title: "feat: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please focus on user-facing outcomes and security impact.
  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight checklist
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
        - label: This request aligns with ModelAudit's security-focused scope.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior you'd like to see.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches you evaluated.
  - type: textarea
    id: security
    attributes:
      label: Security considerations
      description: Any expected effect on detection coverage, false positives, or risk posture.
